// Code generated by mockery v2.16.0. DO NOT EDIT.

package mock

import (
	context "context"

	model "github.com/hereisajvi/noty/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MessageService is an autogenerated mock type for the MessageService type
type MessageService struct {
	mock.Mock
}

type MessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageService) EXPECT() *MessageService_Expecter {
	return &MessageService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, message
func (_m *MessageService) Create(ctx context.Context, message model.MessageBusinessObject) (model.MessageDataTransferObject, error) {
	ret := _m.Called(ctx, message)

	var r0 model.MessageDataTransferObject
	if rf, ok := ret.Get(0).(func(context.Context, model.MessageBusinessObject) model.MessageDataTransferObject); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Get(0).(model.MessageDataTransferObject)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.MessageBusinessObject) error); ok {
		r1 = rf(ctx, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MessageService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - message model.MessageBusinessObject
func (_e *MessageService_Expecter) Create(ctx interface{}, message interface{}) *MessageService_Create_Call {
	return &MessageService_Create_Call{Call: _e.mock.On("Create", ctx, message)}
}

func (_c *MessageService_Create_Call) Run(run func(ctx context.Context, message model.MessageBusinessObject)) *MessageService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.MessageBusinessObject))
	})
	return _c
}

func (_c *MessageService_Create_Call) Return(_a0 model.MessageDataTransferObject, _a1 error) *MessageService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MessageService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MessageService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MessageService_Expecter) Delete(ctx interface{}, id interface{}) *MessageService_Delete_Call {
	return &MessageService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MessageService_Delete_Call) Run(run func(ctx context.Context, id string)) *MessageService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MessageService_Delete_Call) Return(_a0 error) *MessageService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MessageService) List(ctx context.Context) ([]model.MessageDataTransferObject, error) {
	ret := _m.Called(ctx)

	var r0 []model.MessageDataTransferObject
	if rf, ok := ret.Get(0).(func(context.Context) []model.MessageDataTransferObject); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MessageDataTransferObject)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MessageService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MessageService_Expecter) List(ctx interface{}) *MessageService_List_Call {
	return &MessageService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MessageService_List_Call) Run(run func(ctx context.Context)) *MessageService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MessageService_List_Call) Return(_a0 []model.MessageDataTransferObject, _a1 error) *MessageService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Update provides a mock function with given fields: ctx, id, message
func (_m *MessageService) Update(ctx context.Context, id string, message model.MessageBusinessObject) (model.MessageDataTransferObject, error) {
	ret := _m.Called(ctx, id, message)

	var r0 model.MessageDataTransferObject
	if rf, ok := ret.Get(0).(func(context.Context, string, model.MessageBusinessObject) model.MessageDataTransferObject); ok {
		r0 = rf(ctx, id, message)
	} else {
		r0 = ret.Get(0).(model.MessageDataTransferObject)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, model.MessageBusinessObject) error); ok {
		r1 = rf(ctx, id, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MessageService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - message model.MessageBusinessObject
func (_e *MessageService_Expecter) Update(ctx interface{}, id interface{}, message interface{}) *MessageService_Update_Call {
	return &MessageService_Update_Call{Call: _e.mock.On("Update", ctx, id, message)}
}

func (_c *MessageService_Update_Call) Run(run func(ctx context.Context, id string, message model.MessageBusinessObject)) *MessageService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.MessageBusinessObject))
	})
	return _c
}

func (_c *MessageService_Update_Call) Return(_a0 model.MessageDataTransferObject, _a1 error) *MessageService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewMessageService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMessageService creates a new instance of MessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMessageService(t mockConstructorTestingTNewMessageService) *MessageService {
	mock := &MessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
