name: "[lint, test, build]"

on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19.x
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      - name: Run linters
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50.1
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19.x
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      - name: Run unit tests
        run: make test
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19.x
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      - name: Build binary file
        run: make build
